# Create a program that will play the “cows and bulls” game with the user. The game works like this:

# Randomly generate a 4-digit number. Ask the user to guess a 4-digit number.
# For every digit that the user guessed correctly in the correct place, they have a “cow”.
# For every digit the user guessed correctly in the wrong place is a “bull.”
# Every time the user makes a guess, tell them how many “cows” and “bulls” they have.
# Once the user guesses the correct number, the game is over.
# Keep track of the number of guesses the user makes throughout the game and tell the user at the end.

# Say the number generated by the computer is 1038. An example interaction could look like this:

#   Welcome to the Cows and Bulls Game!
#   Enter a number:
#   >>> 1234
#   2 cows, 0 bulls
#   >>> 1283
#   1 cow, 2 bull

import random
from colorama import Fore, init
init(autoreset=True)


def cow_check(player: str, pc: str):
    cows = 0
    bulls = 0
    for i in range(4):
        if pc[i] == player[i]:
            cows += 1
        elif player[i] in pc:
            bulls += 1
    return cows, bulls


def generate_number():
    numbers = list(range(10))
    random.shuffle(numbers)
    while numbers[0] == 0:
        random.shuffle(numbers)
    return int("".join(map(str, numbers[::3])))


computer_number = generate_number()
attempts = 0
while True:
    try:
        player_number = int(
            input(Fore.LIGHTBLUE_EX + "\nEnter your 4 digit number:\n"))
        if player_number == 6666:
            print(computer_number)
        if 1000 <= player_number <= 9999:
            attempts += 1
            if player_number == computer_number:
                print(Fore.GREEN +
                      f"You guessed the number in {attempts} attempts!\n")
                attempts = 0
                play_again = input(
                    Fore.YELLOW + "Press Enter to play again, Q to quit: ")
                if play_again.lower() == "q":
                    print(Fore.MAGENTA + "Thanks for playing!")
                    break
            else:
                cows, bulls = cow_check(
                    str(player_number), str(computer_number))
                print(Fore.LIGHTCYAN_EX + f"cows: {cows} bulls: {bulls}")
        else:
            print(Fore.RED + "Please enter a number between 1000 and 9999")
            continue
    except ValueError:
        print(Fore.RED + "Please enter a number between 1000 and 9999")
